version: '3.5'
services:
  mysql:
    env_file: ./.env
    image: mysql:8
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
        - SYS_NICE  # CAP_SYS_NICE
    volumes:
        - ./data/db:/var/lib/mysql
    restart: always
    ports:
        - '3306:3306'
    environment:
        'MYSQL_DATABASE': '${DB_DATABASE}'
        'MYSQL_ROOT_PASSWORD': '${DB_PASSWORD}'
